# @package _global_
defaults:
- online
- _self_
paths:
  compile_cache: ${oc.env:WAM_COMPILE_CACHE,${paths.cache}/torch_compile}
model:
  mot_checkpoint_mixed_attn: false
  mot_compile_mode: reduce-overhead
  mot_compile_gradient_checkpointing: true
  mot_compile_action_context_pad_to: 1024
  video_dit_config:
    use_gradient_checkpointing: false
  action_dit_config:
    use_gradient_checkpointing: false
